/**
 * RPS API
 * Rock, paper & scissors
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ModelError { 
    /**
     * A human readable error message
     */
    message: string;
}