/**
 * RPS API
 * Rock, paper & scissors
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The codes of the different possible moves to play
 */
export type MoveCodeEnum = 'ROCK' | 'PAPER' | 'SCISSORS' | 'LIZARD' | 'SPOCK';

export const MoveCodeEnum = {
    ROCK: 'ROCK' as MoveCodeEnum,
    PAPER: 'PAPER' as MoveCodeEnum,
    SCISSORS: 'SCISSORS' as MoveCodeEnum,
    LIZARD: 'LIZARD' as MoveCodeEnum,
    SPOCK: 'SPOCK' as MoveCodeEnum
};