/**
 * RPS API
 * Rock, paper & scissors
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The codes of every possible outcome of the play
 */
export type OutcomeCodeEnum = 'USER_WINS' | 'MACHINE_WINS' | 'TIE';

export const OutcomeCodeEnum = {
    USERWINS: 'USER_WINS' as OutcomeCodeEnum,
    MACHINEWINS: 'MACHINE_WINS' as OutcomeCodeEnum,
    TIE: 'TIE' as OutcomeCodeEnum
};